# ---
# - name: Provision Operator Snapshot
#   include_tasks: provision_snapshotoperator.yaml
#   vars:
#     snapshot_operator_project: "openshift-marketplace"

- name: Provision OpenShift Container Storage
  include_tasks: provision_ocs.yaml
  vars:
    ocs_project: "{{ ocp4_workload_3scale_servicemesh_demo_ocs_storage_namespace }}"
    snapshot_operator_project: "openshift-marketplace"

- name: Provision 3scale
  include_tasks: provision_threescale.yaml
  vars:
    threescale_project: "3scale"
    ossm_project: "istio-system"
    ocs_project: "{{ ocp4_workload_3scale_servicemesh_demo_ocs_storage_namespace }}"   



